#!/usr/bin/bash

# executed commands are printed to the terminal
set -x

# makes sure we're in the public HTML directory
cd www

# makes sure all users exist for the base (mmcplatform)
wp-cli-php /usr/bin/wp-cli.phar user create user1 user1@domain.com --role=administrator --user_pass='[redacted]' --allow-root --url=http://mmcplatform.com/wp/
wp-cli-php /usr/bin/wp-cli.phar user create user2 user2@domain.com --role=administrator --user_pass='[redacted]' --allow-root --url=http://mmcplatform.com/wp/
wp-cli-php /usr/bin/wp-cli.phar user create user3 user2@domain.com --role=administrator --user_pass='[redacted]' --allow-root --url=http://mmcplatform.com/wp/
# ... and so on

# makes list of users on the base
userlist=$(wp-cli-php /usr/bin/wp-cli.phar user list --field=user_login --format=csv);

# queries all existing sites
sitelists=$(wp-cli-php /usr/bin/wp-cli.phar site list --field=url --format=csv);

# loops through list of all sites,
# then loops through list of all users,
# and assigns each user to each site
#
for i in $(echo $sitelists | sed "s/,/ /g");
do (
  for j in $(echo $userlist | sed "s/,/ /g");
    do ( wp-cli-php /usr/bin/wp-cli.phar  user set-role "$j" administrator --url="$i" ); done;
);
done